POSTGRESQL_DB_NAME = "db_e_commerce"
POSTGRESQL_USERNAME = "postgres"
POSTGRESQL_PASSWORD = "postgres"
POSTGRESQL_URL = "postgres"
POSTGRESQL_PORT = 5432

REDIS_USERNAME = "redis"
REDIS_PASSWORD = "redis"
REDIS_URL = f"redis://{REDIS_USERNAME}:{REDIS_PASSWORD}@redis:6379"
